### ISSUE TITLE
Neato: support for private implementations?

### ISSUE THREAD

**Issue by S-Przybylski** [Santobert/home-assistant#9]
## The problem

Hi @Santobert 
I saw the upcoming change of the neato authentication method in the current home assistant dev. 
Currently I use my credentials to connect the D7 to HA. My HA installation is private. I don't have a open proxy, Nabu Casa or simillar. 
Is it possible to use the new authentication method without having an external url accessible (perhaps i got something wrong)? If not could it be possible to use the old credential style for neato d7 in parallel?
Thanks in advance

## Environment

- Home Assistant Core release with the issue: current dev
- Last working Home Assistant Core release (if known):  0.119.0.dev20201216
- Operating environment (OS/Container/Supervised/Core): docker HA core on RASPI
- Integration causing this issue: neato
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/neato

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by Santobert** [comment]
I'll answer your question even tho this is not an official Q+A forum. Please open an issue in the core repository for issues und bugs and use the [official forum](https://community.home-assistant.io/) or [Discord](https://discord.gg/c5DvZ4e) for general questions.

Your instance doesn't have to be reachable from the internet in order to work with the updated neato integration. But your instance have to be accessible via HTTPS. You can read about this [here](https://www.home-assistant.io/integrations/http/). In fact you need a SSL Certificate and a SSL Key. [Both can be created by yourself if you want this. ](https://stackoverflow.com/a/10176685)

**Comment by S-Przybylski** [comment]
Danke für die schnelle Antwort/thanks for the fast reaction!
